<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diffbot">

  <xacro:macro name="diffbot" params="prefix">
  <xacro:include filename="/home/mg/ws2/install/realsense2_description/share/realsense2_description/urdf/_d435i.urdf.xacro"/>
  <xacro:include filename="/home/mg/ws2/install/realsense2_description/share/realsense2_description/urdf/_d435i_imu_modules.urdf.xacro"/>

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="0.5" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value="0.178" />
  <xacro:property name="base_length" value="0.2" />
  <xacro:property name="base_height" value="0.05" />
  <xacro:property name="wheel_mass" value="0.5" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.0428" />
  <xacro:property name="wheel_radius" value="0.05125" />
  <xacro:property name="wheel_offset_y" value="0.1115" />
  <xacro:property name="caster_wheel_mass" value="0.2" /> <!-- arbitrary value for caster wheel mass -->
  <xacro:property name="caster_wheel_radius" value="0.033" />
  <xacro:property name="z_offset" value="-${base_height/2}" /> <!-- Space btw top of beam and the each joint -->
  <!-- base footprint-->
  <link name="${prefix}base_footprint">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>
    </link>
  <joint name="${prefix}base_joint" type="fixed">
      <parent link="${prefix}base_footprint"/>
      <child link="${prefix}base_link"/>
      <origin xyz="${-base_length/2} 0 ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 0 0"/>
  </joint>
  <!-- *********************** Base Link *********************** -->
  <link name="${prefix}base_link"/>




<!-- *********************** d435i *********************** -->

  <xacro:sensor_d435i parent="base_link" use_nominal_extrinsics="false">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </xacro:sensor_d435i>
<!-- *********************** caster rear wheel Link *********************** -->

    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel"/>
      <origin xyz="0 -${wheel_offset_y} ${wheel_radius}" rpy="${PI/2} 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- left wheel Link -->
    <link name="${prefix}left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
      </link>
<!-- *********************** caster rear wheel Link *********************** -->

    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel"/>
      <origin xyz="0  ${wheel_offset_y} ${wheel_radius}" rpy="${PI/2} 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- right wheel Link -->
    <link name="${prefix}right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      </link>
    <!-- *********************** caster rear wheel Link *********************** -->

    <joint name="${prefix}caster_rear_wheel_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}caster_rear_wheel"/>
      <origin xyz="${-base_width + caster_wheel_radius} 0 ${caster_wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}caster_rear_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}"/>
        </inertial>
      </link>
  <!-- *********************** LIDAR SETUP **********************************  -->
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-.120 0 .080" rpy="0 0 ${PI}"/>
  </joint>

  <link name="base_scan">
  
    <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
      <cylinder radius="0.0508" length="0.080"/>
     </geometry>
    </collision>
    
    <visual>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
      <cylinder radius="0.0508" length="0.08"/>
     </geometry>
     <material name="Black">
          <color rgba="${0/255} ${0/255} ${0/255} 1.0"/>
     </material>
    </visual>
  </link>
  <gazebo reference="base_scan">
    <sensor type="ray" name="head_rplidar_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>3000</samples><!-- 0.12 degrees -->
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.15</min>
          <max>6.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_rplidar_controller" filename="libgazebo_ros_laser.so">
        <topicName>scan</topicName>
        <frameName>base_scan</frameName>
      </plugin>
    </sensor>

 
  </gazebo>
  <gazebo>
         <plugin name="diffbot_diff_drive" filename="libgazebo_ros_diff_drive.so">

      <ros>
        <!-- <namespace>/tb3</namespace> -->
      </ros>

      <update_rate>30</update_rate>

      <!-- wheels -->
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_Wheel_joint</right_joint>

      <!-- kinematics -->
      <wheel_separation>0.287</wheel_separation>
      <wheel_diameter>0.111</wheel_diameter>

      <!-- limits -->
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <command_topic>cmd_vel</command_topic>

      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>false</publish_wheel_tf>

      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
      <publishWheelJointState>true</publishWheelJointState>

    </plugin>
    </gazebo>
  </xacro:macro>

</robot>
